# apiVersion: v1
# kind: Service
# metadata:
#   name: fydp-service
# spec:
#   type: NodePort
#   selector:
#     app: fydp-app
#   ports:
#     - port: 80
#       targetPort: 3000
#       nodePort: 30007

apiVersion: v1
kind: Service
metadata:
  name: fydp-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: fydp-app
